name: Kubernetes-deployment

on:
  workflow_run:
    workflows: [build and push docker image]
    types:
      - completed
jobs:
 deploy:
   name: Create k8s deployment
   runs-on: kubernetes-runner
   steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
     
      - name: Download kubectl binaries
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
     
      - name: Install Kubectl
        run: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      
      - name: Deploy the application
        run: |
          kubectl apply -f https://raw.githubusercontent.com/vharshni/key-store-gin/main/Kubernetes/svc.yaml
          kubectl apply -f https://raw.githubusercontent.com/vharshni/key-store-gin/main/Kubernetes/deply.yaml
          kubectl apply -f https://raw.githubusercontent.com/vharshni/key-store-gin/main/Kubernetes/ingress.yaml
